### ISSUE TITLE
Remote Access Hadoop Instance 

### ISSUE THREAD

**Issue by zeeshan949** [sequenceiq/hadoop-docker#13]
When i access hadoop container from my windows machine from java code.

Windows: 8.1
Hadoop Version: 2.5.1
Docker Container Port bind:
0.0.0.0:8030->8030/tcp, 0.0.0.0:8031->8031/tcpOS: Windows 8.1

CODE:
Configuration conf = new Configuration();
conf.set("fs.default.name", "hdfs://192.168.59.103:8030/user/zeeshan");
conf.set("mapred.job.tracker", "192.168.59.103:8031");
conf.set("hadoop.job.ugi", "hbase");
FileSystem hdfs = FileSystem.get(conf);
hdfs.createNewFile(new Path("/user/zeeshan/test"));

ERROR:
org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN]

**Comment by ambodi** [comment]
@matyix when I try to run the following on my digital ocean instance,
```bash
route add -net 172.17.0.1/16 PUBLIC_IP_DIGITALOCEAN
````

I got the `172.17.0.1/16` part from `docker inspect CONTAINER_ID`:

```
"Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.1",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:01",
        "NetworkID": "47ffe0226df03f93b5f5dee6b8ae2eb8ae802984e5f72328b47e5eebb8288ff4",
```
But I get the following error after running that both inside and outside the container:

```
route: netmask doesn't match route address
Usage: route [-nNvee] [-FC] [<AF>]           List kernel routing tables
       route [-v] [-FC] {add|del|flush} ...  Modify routing table for AF.

       route {-h|--help} [<AF>]              Detailed usage syntax for specified AF.
       route {-V|--version}                  Display version/author and exit.

        -v, --verbose            be verbose
        -n, --numeric            don't resolve names
        -e, --extend             display other/more information
        -F, --fib                display Forwarding Information Base (default)
        -C, --cache              display routing cache instead of FIB

  <AF>=Use '-A <af>' or '--<af>'; default: inet
  List of possible address families (which support routing):
    inet (DARPA Internet) inet6 (IPv6) ax25 (AMPR AX.25)
    netrom (AMPR NET/ROM) ipx (Novell IPX) ddp (Appletalk DDP)```

**Comment by keyki** [comment]
You don't need routing on linux, it is required on OSX and Windows, because of boot2docker.

**Comment by ambodi** [comment]
@keyki thanks for the help.

Okay, I get it.

But then after running the container, I cannot see the jobtracker UI (PUBLIC_IP_DIGITALOCEAN: 50060), what could be the issue?

**Comment by keyki** [comment]
Run the container with `--net=host` and it should work.

**Comment by ambodi** [comment]
nope, did not fix it. @keyki. 

which port is bound to container's UI?

**Comment by keyki** [comment]
If you launch the container with net=host all the ports are available on the host as well. You need to check 2 things:
* Is the task tracker running?
* Is the port available for outside communication in the security group in DigitalOcean.

As a test check the Resource Manager UI on port 8088.
