### ISSUE TITLE
Hadoop 2.4.1

### ISSUE THREAD

**Issue by hellowin** [sequenceiq/hadoop-docker#23]
[Hadoop 2.4.1 official repository](http://www.eu.apache.org/dist/hadoop/common/hadoop-2.4.1/hadoop-2.4.1.tar.gz) is not found. I manually checked to their repository, and it's gone. So when build from Dockerfile it will broken because there are no file to download.

**Comment by matyix** [comment]
Thanks for letting us know and for the proposes source location. All the core Hadoop distributions are available at the Apache archive, see in particular for [Hadoop 2.4.1](https://archive.apache.org/dist/hadoop/core/hadoop-2.4.1). I will update all the Docker files accordingly.

**Comment by hellowin** [comment]
Thank you for the link to the archive, my pull already updated to that repository https://github.com/sequenceiq/hadoop-docker/pull/24

**Comment by matyix** [comment]
Closed by #24
