### ISSUE TITLE
Why does libhadoop.so need fixing?

### ISSUE THREAD

**Issue by dminkovsky** [sequenceiq/hadoop-docker#25]
If you have a minute, could you please explain [these lines](https://github.com/sequenceiq/hadoop-docker/blob/15fd0c0486d0e07085c2082967c7ac6c2bbd7312/Dockerfile#L59-L61)? Thank you.

**Comment by dminkovsky** [comment]
This, I am guessing? http://askubuntu.com/questions/476934/problem-with-hadoop-start-dfs-sh

**Comment by matyix** [comment]
Yes, there is no 64b version distributed by default, thus we are building one.
