### ISSUE TITLE
Hadoop components 

### ISSUE THREAD

**Issue by varmad** [sequenceiq/hadoop-docker#27]
It could be useful if this includes HBase, Hive, Flume, Oozie, Pig, Spark, Tez, and ZooKeeper installations. 

Thanks,
Varma

**Comment by matyix** [comment]
That is the Ambari container - has all (or any other) Hadoop services you have mentioned - based on a Blueprint. For further details read this post, that will guide yu to the container.

http://blog.sequenceiq.com/blog/2014/12/04/multinode-ambari-1-7-0/
