### ISSUE TITLE
Native libs tarball for hadoop 2.7.0 is missing

### ISSUE THREAD

**Issue by sroegner** [sequenceiq/hadoop-docker#31]
Step 34 : RUN curl -Ls http://dl.bintray.com/sequenceiq/sequenceiq-bin/hadoop-native-64-2.7.0.tar | tar -x -C /usr/local/hadoop/lib/native/
 ---> Running in 0f8ccfecd6ef
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

**Comment by roacobb** [comment]
The latest version that is available from that sequenceiq tar set is '2.6.0'. Replacing '2.7.0' with that version will complete the 'docker build' process.

**Comment by sroegner** [comment]
Understood. I just thought it would be nice if someone could put the 2.7.0 tarball in place.

**Comment by lalyos** [comment]
Thanks for reporting it. Just released the 2.7.0 to binary
