### ISSUE TITLE
Expose HDFS Port also to Guest OS

### ISSUE THREAD

**Issue by vinothchandar** [sequenceiq/hadoop-docker#35]
Hi, 

First of all, this is awesome and just what I was looking for to run mini Hadoop locally on Mac OS X. I was trying to write a small program that accessed the HDFS on the docker container from my mac. I think the port 9000 ought to be exposed, for this to happen? 

This is just a one line change in the dockerfile , so let me know if this makes sense or is useful, I can send a patch. 

- V

**Comment by noppanit** [comment]
+1

**Comment by matyix** [comment]
Thanks for reporting - added both namenode ipc defaults (8020 and 9000).
