### ISSUE TITLE
2.7.1 tag not found in repository docker.io/sequenceiq/hadoop-docker

### ISSUE THREAD

**Issue by talSofer** [sequenceiq/hadoop-docker#40]
Hey, 
I'm trying to pull Hadoop 2.7.1 image without success (with - docker pull sequenceiq/hadoop-docker:2.7.1)
I'm using docker toolbox on macOS and already made it to pull and run 2.7.0 image. is 2.7.1 is the right tag? what am I missing? 
 
Thanks in advance,
Tal

**Comment by keyki** [comment]
Hey,

It looks like we didn't create the 2.7.1 tag yet, so please pull it without tag (sequenceiq/hadoop-docker) the latest one is Hadoop 2.7.1

**Comment by talSofer** [comment]
do you mean to pull it using docker pull sequenceiq/hadoop-docker:latest command? 
I'd already tried it and the pulled image was of 2.7.0 version

**Comment by keyki** [comment]
I just triggered a build on docker hub with 2.7.1 tag, but it can take hours. You can also build you own
```
git clone https://github.com/sequenceiq/hadoop-docker.git
cd hadoop-docker && git checkout 2.7.1
docker build -t sequenceiq/hadoop-docker:2.7.1 .
```

**Comment by talSofer** [comment]
building it caused the following error - 
Step 15 : RUN curl -Ls http://dl.bintray.com/sequenceiq/sequenceiq-bin/hadoop-native-64-2.7.1.tar | tar -x -C /tmp/native
 ---> Running in 9b2c0210f3a1
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
The command '/bin/sh -c curl -Ls http://dl.bintray.com/sequenceiq/sequenceiq-bin/hadoop-native-64-2.7.1.tar | tar -x -C /tmp/native' returned a non-zero code: 2

**Comment by keyki** [comment]
Yes, it looks like the native libs are missing, we'll fix it soon, meanwhile please use the 2.7.0 then. Thanks for reporting it.

**Comment by talSofer** [comment]
Thanks for your help!

**Comment by lalyos** [comment]
native-libs 2.7.1 got released: https://github.com/sequenceiq/docker-hadoop-build/releases
so now `sequenceiq/hadoop-docker:2.7.1` is built n dockerhub.

**Comment by talSofer** [comment]
Hey,
Thanks for your prompt response. 
It's working now but this warning appears:
15/12/15 03:50:09 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

**Comment by lalyos** [comment]
hmm that is strange, as the .so is in the correct dir. Could you figure out why this warning is shown?

But anyway this container is for testing/playing didnt meant for production use, so this warning shouldnt be critical.
