### ISSUE TITLE
Yum Checksum Issue When Updating `libselinux`

### ISSUE THREAD

**Issue by cheapRoc** [sequenceiq/hadoop-docker#62]
I'm using this project to establish a test container before we rebuild it using our own foundation images. During a `docker build` of `master` I was unable to get past updating libselinux.

```text
Rpmdb checksum is invalid: dCDPT(pkg checksums): libselinux-utils.x86_64 0:2.0.94-7.el6 - u

The command '/bin/sh -c yum update -y libselinux' returned a non-zero code: 1
```

**Comment by cheapRoc** [comment]
I found my answer on [another project](https://github.com/CentOS/sig-cloud-instance-images/issues/15).  It worked here. Simply add `yum clean all` after every `yum install` or `yum update`.

Relevant bits of my `Dockerfile`...

```diff
 # install dev tools
-RUN yum clean all; \
-    rpm --rebuilddb; \
-    yum install -y curl which tar sudo openssh-server openssh-clients rsync
+RUN yum clean all \
+    && rpm --rebuilddb \
+    && yum install -y curl which tar sudo openssh-server openssh-clients rsync \
+    && yum clean all \
+    && yum update -y libselinux \
+    && yum clean all
+
 # update libselinux. see https://github.com/sequenceiq/hadoop-docker/issues/14
-RUN yum update -y libselinux
+# RUN yum update -y libselinux
```

My issue is resolved, only posting here in case someone else runs across it too.

**Comment by joelplucas** [comment]
It solved my issue too. Thanks!

**Comment by voidfunction** [comment]
Thanks for your kindly recording！ It solved my issue too.

**Comment by Htag** [comment]
Thanks solved mine too
